attrs:
  title: turbulence
  description: Example ingest for ADV data processed using DOLfYN
  location_id: adv
  dataset_name: turbulence
  data_level: a1
  # qualifier:
  # temporal:
  # institution:

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
  dir:
    dims: [dir]
    dtype: str
    attrs:
      description: "Coordinate axes given the reference frame (`ds.coord_sys`)"
      units: "1"
  beam:
    dims: [beam]
    dtype: int
    attrs:
      description: "Beam coordinate axes"
      units: "1"
  inst:
    dims: [inst]
    dtype: str
    attrs:
      description: "Instrument coordinate axes"
      units: "1"
  earth:
    dims: [earth]
    dtype: str
    attrs:
      description: "Earth coordinate axes"
      units: "1"
  tke:
    dims: [tke]
    dtype: str
    attrs:
      description: "Turbulent kinetic energy components"
      units: "1"
  tau:
    dims: [tau]
    dtype: str
    attrs:
      description: "Reynolds stress components"
      units: "1"

data_vars:
  velocity:
    dims: [dir, time]
    dtype: float
    attrs:
      description: "Measured water velocity"
      units: "m/s"
  tke_vector:
    dims: [tke, time]
    dtype: float
    attrs:
      description:
        "Turbulent kinetic energy vector, calculated from the variances of velocity
        (u,v,w)"
      units: "m^2/s^2"
  stress_vector:
    dims: [tau, time]
    dtype: float
    attrs:
      description:
        "Stress vector, calculated from the cross-covariances of velocity (u,v,w)"
      units: "m^2/s^2"
  turbulence_intensity:
    dims: ["time"]
    dtype: float
    attrs:
      description:
        "Ratio of standard deviation of horizontal velocity to horizontal velocity
        magnitude."
      units: "%"
  amplitude:
    dims: [dir, time]
    dtype: float
    attrs:
      description:
        "Amplitude of acoustic signal backscatter, reference relative to instrument"
      units: "dB"
  correlation:
    dims: [dir, time]
    dtype: float
    attrs:
      description: "Broadband acoustic signal correlation as a measure of similarity"
      units: "%"
  heading:
    dims: [time]
    dtype: float
    attrs:
      units: "deg"
  pitch:
    dims: [time]
    dtype: float
    attrs:
      units: "deg"
  roll:
    dims: [time]
    dtype: float
    attrs:
      units: "deg"
  # acceleration:
  #   dims: [dir, time]
  #   dtype: float
  #   attrs:
  #     units: "m/s^2"
  # angular_velocity:
  #   dims: [dir, time]
  #   dtype: float
  #   attrs:
  #     units: "rad/s"
  orientation_matrix:
    dims: [earth, inst, time]
    dtype: float
    attrs:
      description: "Earth (ENU) to instrument (XYZ) orientation matrix"
      units: "1"
  speed_of_sound:
    dims: [time]
    dtype: float
    attrs:
      description:
        "Speed of sound in water calculated in instrument as a funtion of user-specified
        salinity and measured temperature"
      units: "m/s"
  pressure:
    dims: [time]
    dtype: float
    attrs:
      description: "Water pressure at ADCP"
      units: "dbar"
  temperature:
    dims: [time]
    dtype: float
    attrs:
      description: "Water temperature at ADCP"
      units: "deg C"
  orientation_down:
    dims: [time]
    dtype: bool
    attrs:
      description:
        "Nortek flags this as the orientation of the communications cables, which is
        opposite to the ADV head."
      units: "1"
  error:
    dims: [time]
    dtype: int
    attrs:
      description: "Instrument error code"
      units: "1"
  battery_voltage:
    dims: [time]
    dtype: float
    attrs:
      description: "Battery voltage"
      units: "V"
